version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file template.yml --s3-bucket test-art-bklogin --output-template-file package.yml
artifacts:
  type: zip
  files:
    - template.yml
    - package.yml
